import type { ToolMetadata } from './types.js';

const read = (...graphScopes: string[]): ToolMetadata => ({ graphScopes });
const write = (operationType: string, ...graphScopes: string[]): ToolMetadata => ({
  isWriteOperation: true,
  operationType,
  graphScopes
});

export const toolMetadata: Record<string, ToolMetadata> = {
  graph_get_me: read('User.Read'),
  users_list: read('User.ReadBasic.All'),
  users_search: read('User.ReadBasic.All'),
  users_get_profile: read('User.Read.All'),
  users_get_manager: read('User.Read.All'),
  users_list_direct_reports: read('User.Read.All'),
  users_list_memberships: read('User.Read.All'),

  groups_list: read('GroupMember.Read.All'),
  groups_get: read('GroupMember.Read.All'),
  groups_list_members: read('GroupMember.Read.All'),
  groups_list_owners: read('GroupMember.Read.All'),
  groups_check_my_memberships: read('User.Read'),

  mail_list_messages: read('Mail.Read'),
  mail_search_messages: read('Mail.Read'),
  mail_get_message: read('Mail.Read'),
  mail_list_folders: read('Mail.Read'),
  mail_get_folder: read('Mail.Read'),
  mail_list_child_folders: read('Mail.Read'),
  mail_list_folder_messages: read('Mail.Read'),
  mail_create_folder: write('create_mail_folder', 'Mail.ReadWrite'),
  mail_update_folder: write('update_mail_folder', 'Mail.ReadWrite'),
  mail_delete_folder: write('delete_mail_folder', 'Mail.ReadWrite'),
  mail_list_attachments: read('Mail.Read'),
  mail_get_attachment: read('Mail.Read'),
  mail_add_file_attachment: write('add_mail_attachment', 'Mail.ReadWrite'),
  mail_delete_attachment: write('delete_mail_attachment', 'Mail.ReadWrite'),
  mail_send: write('send_email', 'Mail.Send'),
  mail_create_draft: write('create_email_draft', 'Mail.ReadWrite'),
  mail_send_draft: write('send_email', 'Mail.Send'),
  mail_reply: write('send_email', 'Mail.Send'),
  mail_forward: write('send_email', 'Mail.Send'),
  mail_set_read_state: write('update_email', 'Mail.ReadWrite'),
  mail_move_message: write('move_email', 'Mail.ReadWrite'),
  mail_copy_message: write('copy_email', 'Mail.ReadWrite'),
  mail_delete_message: write('delete_email', 'Mail.ReadWrite'),

  calendar_list_events: read('Calendars.Read'),
  calendar_list_view: read('Calendars.Read'),
  calendar_list_calendars: read('Calendars.Read'),
  calendar_create_calendar: write('create_calendar', 'Calendars.ReadWrite'),
  calendar_update_calendar: write('update_calendar', 'Calendars.ReadWrite'),
  calendar_delete_calendar: write('delete_calendar', 'Calendars.ReadWrite'),
  calendar_get_event: read('Calendars.Read'),
  calendar_list_event_instances: read('Calendars.Read'),
  calendar_get_schedule: read('Calendars.Read'),
  calendar_create_event: write('create_event', 'Calendars.ReadWrite'),
  calendar_update_event: write('update_event', 'Calendars.ReadWrite'),
  calendar_cancel_event: write('cancel_event', 'Calendars.ReadWrite'),
  calendar_delete_event: write('delete_event', 'Calendars.ReadWrite'),
  calendar_respond_to_event: write('respond_to_event', 'Calendars.ReadWrite'),
  calendar_list_attachments: read('Calendars.Read'),
  calendar_add_file_attachment: write('add_event_attachment', 'Calendars.ReadWrite'),
  calendar_delete_attachment: write('delete_event_attachment', 'Calendars.ReadWrite'),

  drive_get_drive: read('Files.Read'),
  drive_list_root: read('Files.Read'),
  drive_list_children: read('Files.Read'),
  drive_list_recent: read('Files.Read'),
  drive_search_items: read('Files.Read'),
  drive_get_item: read('Files.Read'),
  drive_download_file: read('Files.Read'),
  drive_create_folder: write('create_drive_folder', 'Files.ReadWrite'),
  drive_upload_small_file: write('upload_drive_file', 'Files.ReadWrite'),
  drive_rename_item: write('rename_drive_item', 'Files.ReadWrite'),
  drive_move_item: write('move_drive_item', 'Files.ReadWrite'),
  drive_copy_item: write('copy_drive_item', 'Files.ReadWrite'),
  drive_delete_item: write('delete_drive_item', 'Files.ReadWrite'),
  drive_create_share_link: write('create_share_link', 'Files.ReadWrite'),
  drive_invite_item: write('invite_drive_item', 'Files.ReadWrite'),
  drive_list_permissions: read('Files.Read'),
  drive_list_versions: read('Files.Read'),
  drive_restore_version: write('restore_drive_version', 'Files.ReadWrite'),

  sharepoint_search_sites: read('Sites.Read.All'),
  sharepoint_get_site: read('Sites.Read.All'),
  sharepoint_get_site_by_path: read('Sites.Read.All'),
  sharepoint_list_lists: read('Sites.Read.All'),
  sharepoint_create_list: write('create_sharepoint_list', 'Sites.Manage.All'),
  sharepoint_update_list: write('update_sharepoint_list', 'Sites.Manage.All'),
  sharepoint_delete_list: write('delete_sharepoint_list', 'Sites.Manage.All'),
  sharepoint_list_columns: read('Sites.Read.All'),
  sharepoint_create_column: write('create_sharepoint_column', 'Sites.Manage.All'),
  sharepoint_update_column: write('update_sharepoint_column', 'Sites.Manage.All'),
  sharepoint_delete_column: write('delete_sharepoint_column', 'Sites.Manage.All'),
  sharepoint_list_list_items: read('Sites.Read.All'),
  sharepoint_list_item_delta: read('Sites.Read.All'),
  sharepoint_get_list_item: read('Sites.Read.All'),
  sharepoint_create_list_item: write('create_sharepoint_list_item', 'Sites.ReadWrite.All'),
  sharepoint_update_list_item: write('update_sharepoint_list_item', 'Sites.ReadWrite.All'),
  sharepoint_delete_list_item: write('delete_sharepoint_list_item', 'Sites.ReadWrite.All'),
  sharepoint_list_drives: read('Sites.Read.All', 'Files.Read.All'),
  sharepoint_list_drive_items: read('Sites.Read.All', 'Files.Read.All'),
  sharepoint_search_drive_items: read('Sites.Read.All', 'Files.Read.All'),
  sharepoint_get_drive_item: read('Sites.Read.All', 'Files.Read.All'),
  sharepoint_download_file: read('Files.Read.All'),
  sharepoint_create_drive_folder: write('create_sharepoint_folder', 'Sites.ReadWrite.All', 'Files.ReadWrite.All'),
  sharepoint_upload_small_file: write('upload_sharepoint_file', 'Sites.ReadWrite.All', 'Files.ReadWrite.All'),
  sharepoint_rename_drive_item: write('rename_sharepoint_drive_item', 'Files.ReadWrite.All'),
  sharepoint_move_drive_item: write('move_sharepoint_drive_item', 'Files.ReadWrite.All'),
  sharepoint_copy_drive_item: write('copy_sharepoint_drive_item', 'Files.ReadWrite.All'),
  sharepoint_create_share_link: write('create_share_link', 'Files.ReadWrite.All'),
  sharepoint_invite_drive_item: write('invite_sharepoint_drive_item', 'Files.ReadWrite.All'),
  sharepoint_list_drive_permissions: read('Files.Read.All'),
  sharepoint_list_drive_versions: read('Files.Read.All'),
  sharepoint_restore_drive_version: write('restore_sharepoint_drive_version', 'Files.ReadWrite.All'),
  sharepoint_delete_drive_item: write('delete_sharepoint_drive_item', 'Sites.ReadWrite.All', 'Files.ReadWrite.All'),

  teams_list_joined_teams: read('Team.ReadBasic.All'),
  teams_get_team: read('Team.ReadBasic.All'),
  teams_list_team_members: read('TeamMember.Read.All'),
  teams_add_team_member: write('add_teams_member', 'TeamMember.ReadWrite.All'),
  teams_remove_team_member: write('remove_teams_member', 'TeamMember.ReadWrite.All'),
  teams_list_channels: read('Channel.ReadBasic.All'),
  teams_get_channel: read('Channel.ReadBasic.All'),
  teams_list_channel_members: read('ChannelMember.Read.All'),
  teams_create_channel: write('create_teams_channel', 'Channel.Create'),
  teams_update_channel: write('update_teams_channel', 'ChannelSettings.ReadWrite.All'),
  teams_delete_channel: write('delete_teams_channel', 'Channel.Delete.All'),
  teams_add_channel_member: write('add_teams_channel_member', 'ChannelMember.ReadWrite.All'),
  teams_remove_channel_member: write('remove_teams_channel_member', 'ChannelMember.ReadWrite.All'),
  teams_list_channel_messages: read('ChannelMessage.Read.All'),
  teams_list_channel_message_replies: read('ChannelMessage.Read.All'),
  teams_send_channel_message: write('send_teams_message', 'ChannelMessage.Send'),
  teams_reply_channel_message: write('send_teams_message', 'ChannelMessage.Send'),
  teams_delete_channel_message: write('delete_teams_message', 'ChannelMessage.ReadWrite'),
  teams_list_chats: read('Chat.Read'),
  teams_create_chat: write('create_teams_chat', 'Chat.Create'),
  teams_list_chat_members: read('Chat.Read'),
  teams_add_chat_member: write('add_teams_chat_member', 'ChatMember.ReadWrite'),
  teams_remove_chat_member: write('remove_teams_chat_member', 'ChatMember.ReadWrite'),
  teams_list_chat_messages: read('Chat.Read'),
  teams_send_chat_message: write('send_teams_message', 'ChatMessage.Send'),
  teams_delete_chat_message: write('delete_teams_message', 'Chat.ReadWrite'),

  contacts_list: read('Contacts.Read'),
  contacts_search: read('Contacts.Read'),
  contacts_get: read('Contacts.Read'),
  contacts_list_folders: read('Contacts.Read'),
  contacts_list_folder_contacts: read('Contacts.Read'),
  contacts_create_folder: write('create_contact_folder', 'Contacts.ReadWrite'),
  contacts_update_folder: write('update_contact_folder', 'Contacts.ReadWrite'),
  contacts_delete_folder: write('delete_contact_folder', 'Contacts.ReadWrite'),
  contacts_create: write('create_contact', 'Contacts.ReadWrite'),
  contacts_update: write('update_contact', 'Contacts.ReadWrite'),
  contacts_delete: write('delete_contact', 'Contacts.ReadWrite'),

  search_mail: { ...read('Mail.Read'), requiredRoles: ['mcp.mail'] },
  search_calendar: { ...read('Calendars.Read'), requiredRoles: ['mcp.calendar'] },
  search_files: { ...read('Files.Read.All'), requiredRoles: ['mcp.drive'] },
  search_sharepoint: { ...read('Sites.Read.All'), requiredRoles: ['mcp.sharepoint'] },
  search_teams: { ...read('Chat.Read'), requiredRoles: ['mcp.teams'] },
  smart_mail_digest: { ...read('Mail.Read', 'User.Read'), requiredRoles: ['mcp.mail'] },
  smart_calendar_conflicts: { ...read('Calendars.Read'), requiredRoles: ['mcp.calendar'] },
  smart_teams_unread: {
    ...read('Team.ReadBasic.All', 'Channel.ReadBasic.All', 'ChannelMessage.Read.All', 'Chat.Read'),
    requiredRoles: ['mcp.teams']
  }
};
